export type RootStackParamList = {
  RootSplashScreen: undefined;
  RootOnboardingScreen1: undefined;
  RootOnboardingScreen2: undefined;
  RootOnboardingScreen3: undefined;
  RootHomeScreen: undefined;
  RootLoginScreen: undefined;
  RootSignupScreen: undefined;
  Signup: undefined;
  Signin: undefined;
  PayPalScreen: undefined;
  AllEventAttendanceScreen: undefined;
  AllDiscountsScreen: undefined;
  AddNewDiscountScreen: undefined;
  ShowProfile: undefined;
  EditProfile: undefined;
  CreateProfile: undefined;
  BuyTicket: undefined;
  TicketInfoScreen: undefined;
  AllTicktsScreen: undefined;
  UserDiscountsScreen: undefined;
};
