export type RootStackParamList = {
  RootSplashScreen: undefined;
  RootOnboardingScreen1: undefined;
  RootOnboardingScreen2: undefined;
  RootOnboardingScreen3: undefined;
  RootHomeScreen: undefined;
  RootLoginScreen: undefined;
  RootSignupScreen: undefined;
  Signup: undefined;
  Signin: undefined;
  PayPalScreen: undefined;
  user: undefined;
  Map: undefined;
  CreateEvent: undefined;
  list: undefined;
  fileplus: undefined;
  ShowProfileScreen: undefined;
  NavigatorForUser: undefined;
  EditEvent: {eventId: string};
  LoginMainRole: undefined;
  OrganizerSigninScreen: undefined;
  AllEventAttendanceScreen: undefined;
  AllDiscountsScreen: undefined;
  AddNewDiscountScreen: undefined;
  ShowProfile: undefined;
  EditProfile: undefined;
  CreateProfile: undefined;
  BuyTicket: undefined;
  TicketInfoScreen: undefined;
  AllTicktsScreen: undefined;
  UserDiscountsScreen: undefined;
  OrgnizerScreens: undefined;
  UserScreens: undefined;
};
